displayName: Dynamic headers rewriter
type: middleware

import: bizaway/headerrules

summary: 'Change Request and Response headers'

testData:
  Headers:
    Request: 
      Header: test
      X-Host:
        source: request
        value: Host
      X-Origin:
        source: request
        value: Origin
    Response:
      Foo:
        source: string
        value: Bar
      X-Original-Url:
        source: request
        value: X-Host
