http:
  routers:
    router1:
      service: whoami
      middlewares:
        - bizawayHeaders
      rule: "Host(`localhost`)"

  middlewares:
    bizawayHeaders:
      plugin:
        bizawayHeaders:
          Headers:
            Request:
              X-Original-Host: "[[.Host]]"
              Host: "custom.endpoint"
            Response:
              Access-Control-Allow-Origin: "https://[[.Request.Header.Get \"X-Original-Host\"]]"

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami"