entryPoints:
  web:
    address: :80

experimental:
  localPlugins:
    bizawayHeaders:
      moduleName: bizaway/headerrules

providers:
  file:
    directory: /etc/traefik/dynamic
log:
  level: DEBUG
